name: build

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        install_url: https://releases.nixos.org/nix/nix-2.8.0/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
    - run: nix build --print-build-logs
    - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      name: Dereference artifact
    - name: Push artifacts
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: ${{ env.UPLOAD_PATH }}/*
